#!/bin/bash
#
# numbrite väljastamine ja summa arvutamine - while
#
summa=0 # määrame summa algväärtuse
k=1 # määrame kordamise algväärtuse
while [ $k -le 5 ]
do
  read -p "Sisesta $k. Number: " n
  summa=$(($summa + $n))
  k=$(($k + 1))
done
echo "Arvude summa on $summa"
